import type { Metadata } from 'next'
import './globals.css'
import { FontSans, FontTitle } from '@/lib/fonts'
import { Navbar } from '@/components/ui/navbar/navbar'
import { cn } from '@/lib/utils/utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body
        className={cn(
          'bg-black flex flex-col items-center min-h-screen text-white font-sans',
          FontSans.variable,
          FontTitle.variable,
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
